# Generated by Django 5.1.1 on 2024-09-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookstoremodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
