# Generated by Django 5.1.1 on 2024-09-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
